import { SettingsAccentName } from './SettingsTypes'

export class SettingsResources {
  static readonly ARROW_LEFT_ICON: Resource = $r('app.media.arrow_left')
  static readonly CHECK_ICON: Resource = $r('app.media.check')
  static readonly OVERVIEW_ICON: Resource = $r('app.media.settings_overview')
  static readonly BASIC_ICON: Resource = $r('app.media.settings_basic')
  static readonly REMOTE_CONTROL_ICON: Resource = $r('app.media.settings_remote_control')
  static readonly PROJECT_HELP_ICON: Resource = $r('app.media.settings_help')
  static readonly REMOTE_SERVICE_ICON: Resource = $r('app.media.settings_remote_service')
  static readonly REMOTE_SCREEN_ICON: Resource = $r('app.media.settings_remote_screen')
  static readonly REMOTE_ACCESS_ICON: Resource = $r('app.media.settings_remote_access')
  static readonly REMOTE_FILES_ICON: Resource = $r('app.media.settings_remote_files')
  static readonly SETTINGS_ICON: Resource = $r('app.media.settings_entry')
  static readonly SYSTEM_ICON: Resource = $r('app.media.settings_system')
  static readonly SUN_ICON: Resource = $r('app.media.settings_light')
  static readonly MOON_ICON: Resource = $r('app.media.settings_dark')
}

export class SettingsAccent {
  static readonly BLUE: SettingsAccentName = 'blue'
  static readonly PURPLE: SettingsAccentName = 'purple'
  static readonly GREEN: SettingsAccentName = 'green'
  static readonly AMBER: SettingsAccentName = 'amber'
  static readonly CYAN: SettingsAccentName = 'cyan'
  static readonly ORANGE: SettingsAccentName = 'orange'
  static readonly INDIGO: SettingsAccentName = 'indigo'
}
