import { Permissions } from '@kit.AbilityKit'

export const HILOG_DOMAIN: number = 0xF3D1
export const HILOG_TAG: string = 'FreeRDPUi'
export const REMOTE_SURFACE_FOCUS_ID: string = 'rdpRemoteSurface'

export const READ_PASTEBOARD_PERMISSION: Permissions = 'ohos.permission.READ_PASTEBOARD'
export const MICROPHONE_PERMISSION: Permissions = 'ohos.permission.MICROPHONE'
export const CAMERA_PERMISSION: Permissions = 'ohos.permission.CAMERA'
export const APPROXIMATE_LOCATION_PERMISSION: Permissions = 'ohos.permission.APPROXIMATELY_LOCATION'
export const LOCATION_PERMISSION: Permissions = 'ohos.permission.LOCATION'
export const SCREEN_RECORDING_PERMISSION: Permissions = 'ohos.permission.CUSTOM_SCREEN_RECORDING'
export const CONTROL_DEVICE_PERMISSION: Permissions = 'ohos.permission.CONTROL_DEVICE'
