export class HomeResources {
  static readonly SEARCH_ICON: Resource = $r('app.media.home_search')
  static readonly MONITOR_ICON: Resource = $r('app.media.home_monitor')
  static readonly SHIELD_ICON: Resource = $r('app.media.home_shield')
  static readonly LOCK_ICON: Resource = $r('app.media.home_lock')
  static readonly COPY_ICON: Resource = $r('app.media.home_copy')
  static readonly LINK_ICON: Resource = $r('app.media.home_link')
  static readonly TRASH_ICON: Resource = $r('app.media.home_trash')
  static readonly CHEVRON_RIGHT_ICON: Resource = $r('app.media.home_chevron_right')
}
