import { SettingsAccentName } from './SettingsTypes';
export declare class SettingsResources {
    static readonly ARROW_LEFT_ICON: Resource;
    static readonly CHECK_ICON: Resource;
    static readonly OVERVIEW_ICON: Resource;
    static readonly BASIC_ICON: Resource;
    static readonly REMOTE_CONTROL_ICON: Resource;
    static readonly PROJECT_HELP_ICON: Resource;
    static readonly REMOTE_SERVICE_ICON: Resource;
    static readonly REMOTE_SCREEN_ICON: Resource;
    static readonly REMOTE_ACCESS_ICON: Resource;
    static readonly REMOTE_FILES_ICON: Resource;
    static readonly SETTINGS_ICON: Resource;
    static readonly SYSTEM_ICON: Resource;
    static readonly SUN_ICON: Resource;
    static readonly MOON_ICON: Resource;
}
export declare class SettingsAccent {
    static readonly BLUE: SettingsAccentName;
    static readonly PURPLE: SettingsAccentName;
    static readonly GREEN: SettingsAccentName;
    static readonly AMBER: SettingsAccentName;
    static readonly CYAN: SettingsAccentName;
    static readonly ORANGE: SettingsAccentName;
    static readonly INDIGO: SettingsAccentName;
}
